### PR TITLE
update all last commit

### PR DESCRIPTION
**Pull request by ddkwork**

### CODE REVIEW

**Comment by ddkwork** [comment]
This PR mainly uses the goki module directly, and no longer uses the old module

**Review by kkoreilly — CHANGES_REQUESTED** [review]
I will approve this once you remove the `pull.cmd` file and gitignore line, remove the `.idea` files, and sync the fork from upstream using the method I described in the gide PR.

**Comment by kkoreilly** [comment]
Can you redo this PR rooted from the main branch? Thanks!

**Comment by ddkwork** [comment]
> Can you redo this PR rooted from the main branch? Thanks!

Ok, I'll try again

**Pull request closed without merging**
